requires 'Modern::Perl';
requires 'utf8::all';
requires 'DateTime';
requires 'DateTime::Format::Pg';
requires 'Mojolicious', '==4.50';
requires 'Try::Tiny', '0';
requires 'DBD::Pg';
requires 'DBIx::Class', '0';
requires 'DBIx::Class::TimeStamp', '0';
requires 'Mojolicious::Plugin::Util::RandomString', '0';
requires 'IO::Socket::SSL', '2';
requires 'App::Sqitch';
requires 'Config::General';
requires 'DBIx::Class::Schema::Loader';
requires 'XML::Mini', '';
requires 'Crypt::CBC', '';
requires 'MIME::Base64::URLSafe', '';
requires 'Crypt::Blowfish', '';
requires 'Email::Valid', '';
requires 'Data::Dumper::HTML', '';
requires 'Mojolicious::Plugin::Mail', '==1.2';
requires 'DBIx::Class::Schema';
requires 'Mojo::Base';
requires 'Sub::Name';
requires 'Crypt::URandom';
requires 'JSON::XS';
requires 'XML::Hash';
requires 'XML::Parser';
requires 'Sub::Util';
